[tool.ruff]
exclude = [".git", ".vscode", ".pytest_cache", ".mypy_cache", ".env"]
line-length = 125

[tool.ruff.lint]
ignore = ["B008", "ISC001", "E501", "W191"]
select = [
    "B",
    "E",
    "F",
    "W",
    "I",
    "N",
    "C4",
    "EXE",
    "ISC",
    "ICN",
    "PIE",
    "PT",
    "RET",
    "SIM",
    "ERA",
    "PLC",
    "RUF",
    "ARG",
]
